# Generated by Django 5.2.8 on 2025-11-15 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mockmap", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                ("body", models.TextField()),
                ("variables", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("website", models.URLField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("google_maps", "Google Maps"), ("apollo", "Apollo")],
                        max_length=50,
                    ),
                ),
                ("rating", models.FloatField(blank=True, null=True)),
                ("reviews_count", models.IntegerField(blank=True, null=True)),
                ("email_verified", models.BooleanField(default=False)),
                ("phone_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scraped", models.BooleanField(default=False)),
                ("verified", models.BooleanField(default=False)),
                ("enriched", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "lead",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status",
                        to="mockmap.lead",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OutreachSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("responded", "Responded"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("email_subject", models.CharField(max_length=255)),
                ("email_body", models.TextField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("response_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mockmap.lead"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OutreachTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence_step", models.IntegerField()),
                ("delivered", models.BooleanField(default=False)),
                ("opened", models.BooleanField(default=False)),
                ("clicked", models.BooleanField(default=False)),
                ("replied", models.BooleanField(default=False)),
                ("last_checked", models.DateTimeField(auto_now=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mockmap.lead"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Item",
        ),
    ]
