# Generated by Django 5.2.8 on 2025-11-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mockmap", "0002_emailtemplate_lead_leadstatus_outreachsequence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="address",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
