# Generated by Django 5.2.8 on 2025-11-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mockmap", "0003_lead_description_alter_lead_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
