# Generated by Django 5.2.8 on 2025-11-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mockmap", "0004_lead_email_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="apollo_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
