# Generated by Django 5.2.8 on 2025-11-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mockmap", "0005_lead_apollo_id_lead_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="keywords",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="linkedin_url",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
