# Generated by Django 5.2.8 on 2025-11-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mockmap", "0006_lead_keywords_lead_linkedin_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="outreachtracking",
            name="follow_up",
            field=models.BooleanField(default=False),
        ),
    ]
