# Generated by Django 5.2.8 on 2025-11-23 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mockmap", "0007_outreachtracking_follow_up"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutreachTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("step", models.IntegerField()),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("version", models.CharField(default="v1", max_length=50)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["step"],
            },
        ),
        migrations.DeleteModel(
            name="EmailTemplate",
        ),
        migrations.RemoveField(
            model_name="outreachtracking",
            name="clicked",
        ),
        migrations.RemoveField(
            model_name="outreachtracking",
            name="delivered",
        ),
        migrations.RemoveField(
            model_name="outreachtracking",
            name="follow_up",
        ),
        migrations.RemoveField(
            model_name="outreachtracking",
            name="last_checked",
        ),
        migrations.RemoveField(
            model_name="outreachtracking",
            name="opened",
        ),
        migrations.RemoveField(
            model_name="outreachtracking",
            name="replied",
        ),
        migrations.RemoveField(
            model_name="outreachtracking",
            name="sequence_step",
        ),
        migrations.AddField(
            model_name="outreachtracking",
            name="event",
            field=models.CharField(
                blank=True,
                choices=[
                    ("delivered", "Delivered"),
                    ("opened", "Opened"),
                    ("clicked", "Clicked"),
                    ("replied", "Replied"),
                    ("bounced", "Bounced"),
                    ("pending", "Pending"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="outreachtracking",
            name="sequence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mockmap.outreachsequence",
            ),
        ),
        migrations.AddField(
            model_name="outreachtracking",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="outreachsequence",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mockmap.outreachtemplate",
            ),
        ),
    ]
