# Generated by Django 5.2.8 on 2025-11-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mockmap", "0008_outreachtemplate_delete_emailtemplate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outreachtracking",
            name="message_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
