# Generated by Django 5.2.8 on 2025-11-24 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mockmap", "0009_outreachtracking_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outreachsequence",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mockmap.outreachtemplate",
            ),
        ),
    ]
