# Generated by Django 5.2.8 on 2025-11-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mockmap", "0010_alter_outreachsequence_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="icp_match",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="icp_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="scored",
            field=models.BooleanField(default=False),
        ),
    ]
