# Generated by Django 5.2.8 on 2025-11-29 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mockmap", "0011_lead_icp_match_lead_icp_reason_lead_scored"),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "content",
                    models.TextField(help_text="Email or outreach template text"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="lead",
            name="website",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="outreachsequence",
            name="template_used",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mockmap.template",
            ),
        ),
    ]
