# Generated by Django 5.2.8 on 2025-11-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mockmap", "0012_template_alter_lead_website_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outreachtracking",
            name="opened_at",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
