# Generated by Django 5.2.8 on 2025-12-01 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mockmap", "0013_outreachtracking_opened_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="template",
            name="sequence_order",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="template",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("first_touch", "First Touch"),
                    ("follow_up", "Follow Up"),
                    ("case_study", "Case Study"),
                ],
                default="first_touch",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("followup_number", models.PositiveIntegerField(default=1)),
                ("template_type", models.CharField(blank=True, max_length=50)),
                ("email_subject", models.CharField(blank=True, max_length=255)),
                ("email_body", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready for Send"),
                            ("sent", "Sent"),
                            ("replied", "Replied"),
                            ("bounced", "Bounced"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("ready_for_followup", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("replied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followups",
                        to="mockmap.lead",
                    ),
                ),
                (
                    "parent_email",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followup_emails",
                        to="mockmap.outreachtracking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Follow Up",
                "verbose_name_plural": "Follow Ups",
                "ordering": ["lead", "followup_number"],
            },
        ),
    ]
