# Generated by Django 5.2.8 on 2025-12-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mockmap", "0014_template_is_active_template_sequence_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="followup",
            name="opened",
            field=models.BooleanField(default=False),
        ),
    ]
