# Generated by Django 5.2.8 on 2025-12-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mockmap", "0015_followup_opened"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outreachtracking",
            name="opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
