# Generated by Django 5.2.8 on 2025-12-01 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mockmap", "0016_alter_outreachtracking_opened_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="followup",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="followup",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mockmap.template",
            ),
        ),
    ]
