# Generated by Django 5.2.8 on 2025-12-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mockmap", "0017_followup_scheduled_at_followup_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="followup",
            name="message_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
