# Generated by Django 5.2.8 on 2025-12-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mockmap", "0018_followup_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("first_touch", "First Touch"),
                    ("follow_up", "Follow Up"),
                    ("case_study", "Case Study"),
                    ("no-opened-follow_up", "Not Opened"),
                ],
                default="first_touch",
                max_length=20,
            ),
        ),
    ]
