# Generated by Django 5.2.8 on 2025-12-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mockmap", "0019_alter_template_template_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("first_touch", "First Touch"),
                    ("follow_up", "Follow Up"),
                    ("follow_up_2", "Follow Up 2"),
                    ("case_study", "Case Study"),
                    ("no-opened-follow_up", "Not Opened"),
                ],
                default="first_touch",
                max_length=20,
            ),
        ),
    ]
