# Generated by Django 5.2.8 on 2025-12-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mockmap", "0020_alter_template_template_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="source",
            field=models.CharField(
                choices=[
                    ("google_maps", "Google Maps"),
                    ("apollo", "Apollo"),
                    ("csv", "CSV File"),
                ],
                max_length=50,
            ),
        ),
    ]
