# Generated by Django 5.2.8 on 2025-12-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mockmap", "0021_alter_lead_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="address",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="linkedin_url",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
